FROM node:16-alpine

# Create app directory
WORKDIR /usr/src/app/dev

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./
COPY yarn.lock ./

RUN yarn
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .
RUN yarn

EXPOSE 3000
CMD [ "yarn", "start" ]